      name: Secret Test

on:
  workflow_dispatch:

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret via env
        env:
          MY_SECRET_ENV: ${{ secrets.MY_SECRET }}
        run: |
          echo "Using secret inside app logic"
          echo "Length of secret is ${#MY_SECRET_ENV}"
